site_name: Kinetic Display
nav:
  - Contents: index.md
  - Introduction: 
    - intro.md
    - prerequisitesoftware.md
  - OrderParts:
    - Order PCBs: ./createandorder/pcb.md
    - Print parts: ./createandorder/3dprints.md
  - Assemble: 
    - Actuators: ./assembly/actuatorassembly.md
    - Digit pcbs: ./assembly/digitpcbassembly.md
