site_name: Kinetic Display
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
      separator: "_"
nav:
  - Contents: index.md
  - Start Here: 
    - Introduction: intro.md
    - Verify REST API Dependencies: verifyapis.md
    - Install Prerequisite Software: prerequisitesoftware.md
  - Parts:
    - Bill of Materials: ./createandorder/bom.md
    - Order PCBs: ./createandorder/pcb.md
    - Parts FDM Fabrication: ./createandorder/3dprints.md
  - Assemble: 
    - Actuators: ./assembly/actuatorassembly.md
    - Digit PCBs: ./assembly/digitpcbassembly.md
    - Deploy Digit Project: ./assembly/deploydigitproject.md
    - Digit PCB Test: ./assembly/digitpcbtest.md
    - Conductor PCB: ./assembly/controllerpcbassembly.md
    - Deploy Conductor Project: ./assembly/deploycontrollerproject.md
    - Conductor PCB Test: ./assembly/controllerpcbtest.md
    - Power Management PCB: ./assembly/powermanagementpcb.md
    - Power Management PCB Test: ./assembly/powermanagementpcbtest.md
    - Buck Module Wiring: ./assembly/buckmodulesandwiring.md
    - UART and Relay Wiring: ./assembly/uartandrelaywiring.md
    - Display Face and PCBs Assembly with Integration Testing: ./assembly/displayfacepcbs.md
    - Backplate and Stand Assembly: ./assembly/backplateassembly.md
    - Segment Assembly and Installation: ./assembly/segmentassembly.md
    - Finishing Touch: ./assembly/finishingtouch.md
  - User Guide:
    - Orientation: ./userguide/orientation.md
    - On/Off Switch: ./userguide/spdtswitch.md
    - Web Service Settings: ./userguide/websettings.md
    - Schedule Creation and Management: ./userguide/schedule.md
    - Table of Human and Alien Digit Type: ./userguide/digittype.md